name: "manual-downloader"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./__download_file__:/app/__download_file__
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true

volumes:
  mongodb_data:
