name: "auto-downloader"

services:
  app:
    build: .
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - redis-mini-storage-network
      - view-network

networks:
  redis-mini-storage-network:
    external: true
  view-network:
    driver: bridge
    name: connect-view

volumes:
  mongodb_data:
