name: "auto-downloader"

services:
  app:
    build: .
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
    - ./__downloading_base___:/app/__downloading_base___ 
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true

volumes:
  mongodb_data:
