name: "auto-downloader"

services:
  app:
    build: .
    ports:
      - "8001:8001"
      - "8002:8002"
    restart: unless-stopped
    volumes:
    - ./templates:/app/templates 
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true

volumes:
  mongodb_data:
