name: "config-manager"

services:
  config-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-manager
    ports:
      - "8002:8002"
    restart: unless-stopped
    volumes:
      - ./templates:/app/templates
      - ./main.py:/app/main.py
    environment:
      REDIS_HOST: my-redis
      REDIS_PORT: 6379
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true
