name: "viewer-cve"

services:
  app:
    build: .
    ports:
      - "8086:8086"
    restart: unless-stopped
    networks:
      - redis-mini-storage-network
      - connect-view

networks:
  connect-view:
    external: true
  redis-mini-storage-network:
    external: true

volumes:
  mongodb_data: