name: "viewer-cve"

services:
  app:
    build: .
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    restart: unless-stopped
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true

volumes:
  mongodb_data:
