name: "manual-downloader"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - redis-mini-storage-network
  app:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./__download_file__:/app/__download_file__
    networks:
      - redis-mini-storage-network

  mongo-express:
    image: mongo-express
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "123"
    restart: unless-stopped
    networks:
      - redis-mini-storage-network

networks:
  redis-mini-storage-network:
    external: true
  
volumes:
  mongodb_data: